from .persona import Persona
from .empleado import Empleado
from .liquidacion_sueldo import Liquidacion_Sueldo
from .devengado import Devengado
from .horas import Horas
from .comision import Comision
from .deducidos import Deducidos
from .tipos_deducidos  import Tipos_Deducidos
from .fsp  import FSP
from .seguridad_social  import Seguridad_Social
from .aportes_parafiscales  import Aportes_Parafiscales
from .prestacion_social import Prestacion_Social