# Generated by Django 4.1.1 on 2022-10-03 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aportes_Parafiscales',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rengo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('sigla', models.CharField(max_length=80)),
                ('recargo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('factor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deducidos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codio_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('forma_pago', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='FSP',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rengo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('sigla', models.CharField(max_length=80)),
                ('recargo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('factor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cc', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=80)),
                ('apellido1', models.CharField(max_length=80)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('correo', models.EmailField(max_length=80)),
                ('celular', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Prestacion_Social',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rengo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seguridad_Social',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rengo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Deducidos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rengo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion_Sueldo',
            fields=[
                ('num_liquidacion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_liquidacion', models.DateField()),
                ('dias_laborados', models.IntegerField()),
                ('sueldo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('codigo_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empleado', to='authApp.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='cc_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Persona', to='authApp.persona'),
        ),
        migrations.CreateModel(
            name='Devengado',
            fields=[
                ('id_devengado', models.IntegerField(primary_key=True, serialize=False)),
                ('auxilio_trandporte', models.CharField(max_length=80)),
                ('total_devengado', models.DecimalField(decimal_places=0, max_digits=7)),
                ('codigo_liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Liquidacion', to='authApp.liquidacion_sueldo')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('lastChangeDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
