# Generated by Django 4.1.1 on 2022-09-18 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aportes_Parafiscales',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rengo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('sigla', models.CharField(max_length=80)),
                ('recargo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('factor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deducidos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codio_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('forma_pago', models.CharField(max_length=80)),
                ('numero_cuenta', models.CharField(max_length=80)),
                ('cesantias', models.CharField(max_length=80)),
                ('pension', models.CharField(max_length=80)),
                ('salud', models.CharField(max_length=80)),
                ('arl', models.CharField(max_length=80)),
                ('porcentaje_arl', models.CharField(max_length=80)),
                ('caja_compensacion', models.CharField(max_length=80)),
                ('centro_costos', models.CharField(max_length=80)),
                ('fecha_ingreso', models.DateField()),
                ('salario', models.DecimalField(decimal_places=0, max_digits=7)),
                ('tipo_salario', models.CharField(max_length=80)),
                ('tipo_empleado', models.CharField(max_length=80)),
                ('tipo_contrato', models.CharField(max_length=80)),
                ('fin_contrato', models.CharField(max_length=80)),
                ('profesion', models.CharField(max_length=80)),
                ('oficio', models.CharField(max_length=80)),
                ('turno', models.CharField(max_length=80)),
                ('horas', models.IntegerField()),
                ('hora_entrada', models.CharField(max_length=80)),
                ('hora_salida', models.CharField(max_length=80)),
                ('inicio_vacaciones', models.DateField()),
                ('fin_vacaciones', models.DateField()),
                ('estado', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='FSP',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rengo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('sigla', models.CharField(max_length=80)),
                ('recargo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('factor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cc', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=80)),
                ('nombre2', models.CharField(max_length=80)),
                ('apellido1', models.CharField(max_length=80)),
                ('apellido2', models.CharField(max_length=80)),
                ('fecha', models.DateField()),
                ('direccion', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=80)),
                ('telefono', models.CharField(max_length=80)),
                ('celular', models.CharField(max_length=80)),
                ('estado_civil', models.CharField(max_length=80)),
                ('tipo_sangre', models.CharField(max_length=80)),
                ('genero', models.CharField(max_length=80)),
                ('descripcion', models.TextField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Prestacion_Social',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rengo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seguridad_Social',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rengo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Deducidos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rengo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion_Sueldo',
            fields=[
                ('num_liquidacion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_liquidacion', models.DateField()),
                ('dias_laborados', models.IntegerField()),
                ('sueldo', models.DecimalField(decimal_places=0, max_digits=7)),
                ('IBC', models.DecimalField(decimal_places=0, max_digits=7)),
                ('neto_pagar', models.DecimalField(decimal_places=0, max_digits=7)),
                ('codigo_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empleado', to='authApp.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='cc_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Persona', to='authApp.persona'),
        ),
        migrations.CreateModel(
            name='Devengado',
            fields=[
                ('id_devengado', models.IntegerField(primary_key=True, serialize=False)),
                ('auxilio_trandporte', models.CharField(max_length=80)),
                ('total_devengado', models.DecimalField(decimal_places=0, max_digits=7)),
                ('codigo_liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Liquidacion', to='authApp.liquidacion_sueldo')),
            ],
        ),
    ]
